### PR TITLE
Overhaul config

### PR DESCRIPTION
**Pull request by a-dg**
Proposed new structure for configuring sites. See the [readme](https://github.com/tacowordpress/taco-theme/blob/config-overhaul/src/app/config/README.md) for syntax and usage.

### CODE REVIEW

**Comment by a-dg** [comment]
@jasand-pereza Please don't wait a year to review this. That would hurt my feelings. My feelings are fragile. Feelings.

**Comment by jasand-pereza** [comment]
That made me laugh.

**Comment by a-dg** [comment]
@jasand-pereza Do you really want to hurt me? Do you really want to make me cry? (Asking for a friend.)

**Comment by jasand-pereza** [comment]
I'll try to look at it today. I promise.

On Wed, Dec 14, 2016 at 9:25 AM, Alan Dague-Greene <notifications@github.com

**Comment by a-dg** [comment]
The views for pagination are there, but the trait is missing. I need to work on restoring the version of the trait that uses views.

**Pull request closed without merging**
